In [3]:
import pandas as pd
import numpy as np
from faker import Faker
import random

fake = Faker()

n = 100000

In [4]:
paises_limpios = ["España", "Francia", "Italia", "Alemania"]

paises_sucios = {
    "España": ["España", "ES", "spain", "Espana"],
    "Francia": ["Francia", "FR", "france"],
    "Italia": ["Italia", "IT", "italy"],
    "Alemania": ["Alemania", "DE", "germany"]
}

clientes = []

for i in range(n):
    
    pais_base = random.choice(paises_limpios)
    pais = random.choice(paises_sucios[pais_base])
    
    if random.random() < 0.02:
        pais = "Unknown"

    nombre = fake.name()
    
    if random.random() < 0.05:
        nombre = None
    
    clientes.append({
        "id_cliente": i,
        "nombre": nombre,
        "pais": pais
    })

df_clientes = pd.DataFrame(clientes)

duplicados = df_clientes.sample(frac=0.03)
df_clientes = pd.concat([df_clientes, duplicados], ignore_index=True)

df_clientes.head()

   id_cliente           nombre     pais
0           0  Gregory Sellers  germany
1           1   Christy Taylor  Francia
2           2       Tammy Hill   España
3           3  Jennifer Wright  Francia
4           4      John Hughes   france

In [5]:
df_clientes.to_csv("../data/raw/clientes.csv", index=False)

In [6]:
productos = ["PC", "Movil", "Tablet", "TV", "Auriculares"]

productos_sucios = {
    "PC": ["PC", "pc", "ordenador"],
    "Movil": ["Movil", "movil", "telefono"],
    "Tablet": ["Tablet", "tablet"],
    "TV": ["TV", "tv"],
    "Auriculares": ["Auriculares", "cascos"]
}

ventas = []

for i in range(n):

    id_cliente = random.randint(0, n-1)

    if random.random() < 0.02:
        id_cliente = 9999999

    prod_base = random.choice(productos)
    producto = random.choice(productos_sucios[prod_base])

    if random.random() < 0.02:
        producto = "unknown"

    fecha = fake.date_between(start_date='-2y', end_date='today')

    if random.random() < 0.03:
        fecha = str(fecha)

    importe = round(random.uniform(10, 2000), 2)

    if random.random() < 0.03:
        importe = str(importe)

    ventas.append({
        "id_venta": i,
        "fecha": fecha,
        "id_cliente": id_cliente,
        "producto": producto,
        "importe": importe
    })

df_ventas = pd.DataFrame(ventas)

df_ventas.head()

   id_venta       fecha  id_cliente producto  importe
0         0  2024-06-05        9177       tv   525.82
1         1  2025-10-24       76245       TV   162.21
2         2  2024-05-28        1188    movil   677.81
3         3  2024-11-29       88332       TV  1663.37
4         4  2025-12-11       39471   cascos    598.5

In [7]:
df_ventas.to_csv("../data/raw/ventas.csv", index=False)

In [8]:
productos_tabla = [
    {"producto": "PC", "categoria": "Dispositivos"},
    {"producto": "Movil", "categoria": "Dispositivos"},
    {"producto": "Tablet", "categoria": "Dispositivos"},
    {"producto": "TV", "categoria": "Dispositivos"},
    {"producto": "Auriculares", "categoria": "Audio"}
]

df_productos = pd.DataFrame(productos_tabla)

df_productos = pd.concat([df_productos, df_productos.iloc[[0]]], ignore_index=True)

df_productos = pd.concat([
    df_productos,
    pd.DataFrame([{"producto": "Consola", "categoria": "Gaming"}])
], ignore_index=True)

df_productos

      producto     categoria
0           PC  Dispositivos
1        Movil  Dispositivos
2       Tablet  Dispositivos
3           TV  Dispositivos
4  Auriculares         Audio
5           PC  Dispositivos
6      Consola        Gaming

In [9]:
df_productos.to_csv("../data/raw/productos.csv", index=False)

In [10]:
df_productos.info()
df_productos.head()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   producto   7 non-null      str
 1   categoria  7 non-null      str
dtypes: str(2)
memory usage: 244.0 bytes

      producto     categoria
0           PC  Dispositivos
1        Movil  Dispositivos
2       Tablet  Dispositivos
3           TV  Dispositivos
4  Auriculares         Audio

In [11]:
df_clientes.to_csv("../data/raw/clientes.csv", index=False)